### ISSUE TITLE
I'd like to share with you an idea

### ISSUE THREAD

**Issue by rianby64** [TakayoshiKochi/script-type-module#1]
Takayoshi, hello!.
I'd like to share with you an idea - [fragments!](https://github.com/m3co/pseudoimport-html)
I know that there's a big work done around Custom Elements. But, I feel that a bit-different approach based on JS could give developers more flexibility.

The goal that I'm following is simple; I'd like to understand if fragments can be used instead of any big framework in order to build apps.

The simple idea that you can import JS code, leaded me to think about importing HTML code. Why HTML import was not developed before? I've more questions and will be for me wonderful if 
1. fragments caught your interest
2. we could have a chat in order to ask more about JS...

Hope I did not distract you.
Have a nice day, Takayoshi.

**Comment by TakayoshiKochi** [comment]
Hi @rianby64 thanks for your point.

I didn't have clarified what this repository (branch from original ES modules polyfill) is for...
It's kinda experimental thing that can import HTML in an ES6 modules way.
So it sounds like there are some commonality with the fragments.

I haven't taken a deeper look, but at a glance it seems to me that you can load HTML snippet using HTML element (`<x-fragment>`).

I have some questions -
1. Once the content of HTML is loaded, will it be attached under the element?
1. If the content is attached then `<script>` is executed, `<style>` is applied, or to avoid the side-effect, does it keep the HTML snippet within some DocumentFragment (as the name suggests)?
1. Can a fragment have dependency? I.e. if a loaded fragment has `<x-fragment>` inside, this sub fragment will be processed accordingly?

**Comment by rianby64** [comment]
@TakayoshiKochi  please, check the referenced issue. Feel free to close this issue.
